/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package excel;
import java.io.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.*;
import javax.swing.plaf.TableUI;
import javax.swing.table.TableModel;

/**
 *
 * @author ILHAM HADISYAH
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    static String username;
    public UI() {
        
        initComponents();
        setLocationRelativeTo(this);
        new Thread(){
            public void run(){
                while(true){
                Calendar kal = new GregorianCalendar();
                int hr = kal.get(Calendar.HOUR_OF_DAY);
                int min = kal.get(Calendar.MINUTE);
                int sc = kal.get(Calendar.SECOND);
                String time = hr+":"+min+":"+sc;
                clock.setText(time);
                }
            }
        }.start();
        palletCode.requestFocus();
        usern.setText("admin : "+username);
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        usern = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        palletCode = new javax.swing.JTextField();
        lotCode = new javax.swing.JTextField();
        lineCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        clock = new javax.swing.JLabel();
        exportExcel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fileName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        remark = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        fileDir = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 520));
        setPreferredSize(new java.awt.Dimension(810, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        usern.setText("admin");

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Pallet Code", "Lot Code", "Line Code", "Time", "Remark", "Date", "admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable.setColumnSelectionAllowed(true);
        dataTable.setDragEnabled(true);
        dataTable.getTableHeader().setReorderingAllowed(false);
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);
        dataTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(0).setMinWidth(26);
            dataTable.getColumnModel().getColumn(0).setMaxWidth(26);
            dataTable.getColumnModel().getColumn(4).setMinWidth(50);
            dataTable.getColumnModel().getColumn(4).setMaxWidth(50);
            dataTable.getColumnModel().getColumn(5).setMinWidth(50);
            dataTable.getColumnModel().getColumn(5).setMaxWidth(60);
        }

        palletCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palletCodeActionPerformed(evt);
            }
        });
        palletCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                palletCodeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                palletCodeKeyTyped(evt);
            }
        });

        lotCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lotCodeKeyPressed(evt);
            }
        });

        lineCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lineCodeKeyPressed(evt);
            }
        });

        jLabel1.setText("Pallet Code");

        jLabel2.setText("Lot Code");

        jLabel3.setText("Line Code");

        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        insert.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                insertKeyPressed(evt);
            }
        });

        clock.setText("00:00:00");

        exportExcel.setText("Export");
        exportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportExcelActionPerformed(evt);
            }
        });

        jButton2.setText("Save As");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        fileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameActionPerformed(evt);
            }
        });

        jLabel4.setText("File Name");

        remark.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery", "Pindah" }));
        remark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                remarkKeyPressed(evt);
            }
        });

        jLabel5.setText("Remark");

        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(date)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usern, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(palletCode, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lotCode, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lineCode, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(remark, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fileDir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(exportExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(update)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(insert)))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usern, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date)
                    .addComponent(clock, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(palletCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(lotCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lineCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insert)
                    .addComponent(update)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(fileDir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportExcel))
                .addGap(45, 45, 45))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 810, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        
        
        
        DefaultTableModel table =(DefaultTableModel) dataTable.getModel();
        Vector a = new Vector();
        if(palletCode.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "null");
        }else if(lotCode.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "null");
        }else if(lineCode.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "null");
        }
        else{
            
            int n = 1;
            for(int e=0;e<table.getRowCount();e++){
            //int lastRow = dataTable.convertRowIndexToView(table.getRowCount() - 1);
            //dataTable.setRowSelectionInterval(lastRow, lastRow);
            //int row = dataTable.getSelectedRow();
            //n+= Integer.parseInt((String) dataTable.getValueAt(row, 0));
            n +=1;
            }
            String tgl = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
            
            a.add(n);
            a.add(palletCode.getText());
            a.add(lotCode.getText());
            a.add(lineCode.getText());
            a.add(clock.getText());
            a.add(remark.getItemAt(remark.getSelectedIndex()));
            a.add(tgl);
            a.add(username);
            table.addRow(a);

            EmptyField();
   
        
        }
        palletCode.requestFocus();
        
       
        
        
        
        
        
    }//GEN-LAST:event_insertActionPerformed

    public void EmptyField() {
        palletCode.setText("");
        lotCode.setText("");
        lineCode.setText("");
    }

    private void palletCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palletCodeActionPerformed

    }//GEN-LAST:event_palletCodeActionPerformed

    private void palletCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_palletCodeKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_palletCodeKeyTyped

    private void insertKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insertKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertKeyPressed

    private void exportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportExcelActionPerformed
        // TODO add your handling code here:   
   if(fileDir.getText().trim().isEmpty()){
       JOptionPane.showMessageDialog(palletCode, "You must choose directory!");
   }else if(fileDir.getText().trim().isEmpty()){
       JOptionPane.showMessageDialog(palletCode, "null Name!");
   }else{
       try{
        DefaultTableModel model =(DefaultTableModel) dataTable.getModel();
        
        String file = fileName.getText();
        String directory = fileDir.getText();
        directory = directory.replace('\\','/');
        FileWriter excel = new FileWriter(directory+'/'+file+".xls");
        for(int i = 0; i < model.getColumnCount(); i++){
            excel.write(model.getColumnName(i) + "\t");
            
        }

        excel.write("\n");

        for(int i=0; i< model.getRowCount(); i++) {
            for(int j=0; j < model.getColumnCount(); j++) {
                excel.write(model.getValueAt(i,j).toString()+"\t");
            }
            excel.write("\n");
        }

        excel.close();

    }catch(IOException e){ System.out.println(e); }
        JOptionPane.showMessageDialog(palletCode, "Saved !");
        fileDir.setText(":");
        fileName.setText("");
   }
        
       
    }//GEN-LAST:event_exportExcelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("choosertitle");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        
      
      fileDir.setText("" + chooser.getSelectedFile());
    } else {
      fileDir.setText("");
    }
        
      
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameActionPerformed

    private void palletCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_palletCodeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== evt.VK_ENTER)
        lotCode.requestFocus();
    }//GEN-LAST:event_palletCodeKeyPressed

    private void lotCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lotCodeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== evt.VK_ENTER)
        lineCode.requestFocus();
    }//GEN-LAST:event_lotCodeKeyPressed

    private void lineCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lineCodeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== evt.VK_ENTER){
        remark.requestFocus();
        remark.showPopup();
        }
        
        
    }//GEN-LAST:event_lineCodeKeyPressed

    private void remarkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remarkKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()== evt.VK_ENTER)
        insert.doClick();
    }//GEN-LAST:event_remarkKeyPressed

    private void dataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMouseClicked
        // TODO add your handling code here:
        int row = dataTable.getSelectedRow();
        palletCode.setText(dataTable.getValueAt(row, 1).toString());
        lotCode.setText(dataTable.getValueAt(row, 2).toString());
        lineCode.setText(dataTable.getValueAt(row, 3).toString());
    }//GEN-LAST:event_dataTableMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        int row = dataTable.getSelectedRow();
        dataTable.setValueAt(palletCode.getText(), row, 1);
        dataTable.setValueAt(lotCode.getText(), row, 2);
        dataTable.setValueAt(lineCode.getText(), row, 3);
        dataTable.setValueAt(clock.getText(), row, 4);
        dataTable.setValueAt(remark.getSelectedItem(), row, 5);
        EmptyField();
       
    }//GEN-LAST:event_updateMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = 010101010101;
         row = dataTable.getSelectedRow();
        if (row == 010101010101){
            JOptionPane.showMessageDialog(rootPane, "please enter a row");
        }else{
        DefaultTableModel model =(DefaultTableModel) dataTable.getModel();
        model.removeRow(row);
        EmptyField();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clock;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel date;
    private javax.swing.JButton exportExcel;
    private javax.swing.JLabel fileDir;
    private javax.swing.JTextField fileName;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lineCode;
    private javax.swing.JTextField lotCode;
    private javax.swing.JTextField palletCode;
    private javax.swing.JComboBox<String> remark;
    private javax.swing.JButton update;
    private javax.swing.JLabel usern;
    // End of variables declaration//GEN-END:variables
}
