/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package excel;
import java.io.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author ILHAM HADISYAH
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        
        initComponents();
        setLocationRelativeTo(this);
        new Thread(){
            public void run(){
                while(true){
                Calendar kal = new GregorianCalendar();
                int hr = kal.get(Calendar.HOUR_OF_DAY);
                int min = kal.get(Calendar.MINUTE);
                int sc = kal.get(Calendar.SECOND);
                String time = hr+":"+min+":"+sc;
                clock.setText(time);
                }
            }
        }.start();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        palletCode = new javax.swing.JTextField();
        lotCode = new javax.swing.JTextField();
        lineCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        clock = new javax.swing.JLabel();
        exportExcel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fileName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        remark = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        fileDir = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(811, 487));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Pallet Code", "Lot Code", "Line Code", "Time", "Remark", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable.setColumnSelectionAllowed(true);
        dataTable.setDragEnabled(true);
        dataTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(dataTable);
        dataTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 490, 490);

        palletCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palletCodeActionPerformed(evt);
            }
        });
        palletCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                palletCodeKeyTyped(evt);
            }
        });
        jPanel1.add(palletCode);
        palletCode.setBounds(530, 70, 230, 20);
        jPanel1.add(lotCode);
        lotCode.setBounds(530, 120, 230, 20);
        jPanel1.add(lineCode);
        lineCode.setBounds(530, 170, 140, 20);

        jLabel1.setText("Pallet Code");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(530, 50, 140, 14);

        jLabel2.setText("Lot Code");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(530, 100, 130, 14);

        jLabel3.setText("Line Code");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(530, 150, 100, 20);

        jButton1.setText("insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(670, 210, 90, 20);

        clock.setText("00:00:00");
        jPanel1.add(clock);
        clock.setBounds(740, 10, 50, 14);

        exportExcel.setText("Export");
        exportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportExcelActionPerformed(evt);
            }
        });
        jPanel1.add(exportExcel);
        exportExcel.setBounds(670, 280, 90, 23);

        jButton2.setText("Save As");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(530, 230, 90, 23);

        fileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameActionPerformed(evt);
            }
        });
        jPanel1.add(fileName);
        fileName.setBounds(530, 280, 140, 20);

        jLabel4.setText("File Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(530, 260, 60, 14);

        remark.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery", "Pindah" }));
        jPanel1.add(remark);
        remark.setBounds(670, 170, 90, 20);

        jLabel5.setText("Remark");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(670, 150, 50, 20);
        jPanel1.add(fileDir);
        fileDir.setBounds(620, 230, 140, 20);
        jPanel1.add(date);
        date.setBounds(500, 10, 0, 0);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 810, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
        DefaultTableModel table = (DefaultTableModel) dataTable.getModel();
        Vector a = new Vector();
        if(palletCode.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "null");
        }else if(lotCode.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "null");
        }else if(lineCode.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "null");
        }
        else{
            int n=1;
            for(int e=0;e<table.getRowCount();e++){
                n +=1;
            }
            String tgl = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
            
            a.add(n);
            a.add(palletCode.getText());
            a.add(lotCode.getText());
            a.add(lineCode.getText());
            a.add(clock.getText());
            a.add(remark.getItemAt(remark.getSelectedIndex()));
            
            a.add(tgl);
            table.addRow(a);

            palletCode.setText("");
            lotCode.setText("");
            lineCode.setText("");
   
        
        }
        
       
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void palletCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palletCodeActionPerformed

    }//GEN-LAST:event_palletCodeActionPerformed

    private void palletCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_palletCodeKeyTyped
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_palletCodeKeyTyped

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void exportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportExcelActionPerformed
        // TODO add your handling code here:   
   if(fileDir.getText().trim().isEmpty()){
       JOptionPane.showMessageDialog(palletCode, "You must choose directory!");
   }else if(fileDir.getText().trim().isEmpty()){
       JOptionPane.showMessageDialog(palletCode, "null Name!");
   }else{
       try{
        DefaultTableModel model =(DefaultTableModel) dataTable.getModel();
        
        String file = fileName.getText();
        String directory = fileDir.getText();
        directory = directory.replace('\\','/');
        FileWriter excel = new FileWriter(directory+'/'+file+".xls");
        for(int i = 0; i < model.getColumnCount(); i++){
            excel.write(model.getColumnName(i) + "\t");
        }

        excel.write("\n");

        for(int i=0; i< model.getRowCount(); i++) {
            for(int j=0; j < model.getColumnCount(); j++) {
                excel.write(model.getValueAt(i,j).toString()+"\t");
            }
            excel.write("\n");
        }

        excel.close();

    }catch(IOException e){ System.out.println(e); }
        JOptionPane.showMessageDialog(palletCode, "Saved !");
        fileDir.setText("");
        fileName.setText("");
   }
        
       
    }//GEN-LAST:event_exportExcelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("choosertitle");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        
      
      fileDir.setText("" + chooser.getSelectedFile());
    } else {
      fileDir.setText("");
    }
        
      
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clock;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel date;
    private javax.swing.JButton exportExcel;
    private javax.swing.JLabel fileDir;
    private javax.swing.JTextField fileName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lineCode;
    private javax.swing.JTextField lotCode;
    private javax.swing.JTextField palletCode;
    private javax.swing.JComboBox<String> remark;
    // End of variables declaration//GEN-END:variables
}
